# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='image_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
