# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_menu_item_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='restaurants',
            field=models.ManyToManyField(to='app.Restaurant'),
        ),
    ]
